// <auto-generated />
using System;
using DataLayer.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250526101910_editInitialData")]
    partial class editInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataLayer.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Img = "Doctors/doctor1.jpg",
                            IsDeleted = false,
                            Name = "Ibrahim Awad",
                            SpecializationId = 1
                        },
                        new
                        {
                            Id = 2,
                            Img = "Doctors/doctor2.jpg",
                            IsDeleted = false,
                            Name = "Ahmed Essawy",
                            SpecializationId = 1
                        },
                        new
                        {
                            Id = 3,
                            Img = "Doctors/doctor4.jpg",
                            IsDeleted = false,
                            Name = "Mohamed Ali",
                            SpecializationId = 2
                        },
                        new
                        {
                            Id = 4,
                            Img = "Doctors/doctor6.jpg",
                            IsDeleted = false,
                            Name = "Nader Hamdy",
                            SpecializationId = 2
                        },
                        new
                        {
                            Id = 5,
                            Img = "Doctors/doctor2.jpg",
                            IsDeleted = false,
                            Name = "Mohamed Zaky",
                            SpecializationId = 2
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description About Internal Medicine",
                            IsDeleted = false,
                            Name = "Internal Medicine",
                            Slug = "InternalMedicine"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description About Pediatrics",
                            IsDeleted = false,
                            Name = "Pediatrics",
                            Slug = "Pediatrics"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description About Surgery",
                            IsDeleted = false,
                            Name = "Surgery",
                            Slug = "Surgery"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Doctor", b =>
                {
                    b.HasOne("DataLayer.Models.Specialization", "specialization")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("specialization");
                });

            modelBuilder.Entity("DataLayer.Models.Specialization", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
