// <auto-generated />
using System;
using DataLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250719103318_WishlistModel")]
    partial class WishlistModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataLayer.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "09ddfbd1-ceb0-4e76-866a-a2dc0bd7eaa2",
                            Email = "super@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Super",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "super@gmail.com",
                            NormalizedUserName = "SUPERADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEHJs+pm20TRbQxAForJ3tGLujeaPE6jeTxN+fr3AgQCBqe08QLHdtc7ZLKWGwsxi2Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c7e872b1-f6a0-47b9-b97b-bafb9c797266",
                            TwoFactorEnabled = false,
                            UserName = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 417, DateTimeKind.Utc).AddTicks(8631),
                            Description = "Hands-on learning sessions",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Workshops",
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 417, DateTimeKind.Utc).AddTicks(8639)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 418, DateTimeKind.Utc).AddTicks(669),
                            Description = "Educational talks by experts",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Lectures",
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 418, DateTimeKind.Utc).AddTicks(671)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 418, DateTimeKind.Utc).AddTicks(676),
                            Description = "Cultural and scientific displays",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Exhibitions",
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 418, DateTimeKind.Utc).AddTicks(676)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 418, DateTimeKind.Utc).AddTicks(679),
                            Description = "Multi-day events with multiple speakers",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Conferences",
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 418, DateTimeKind.Utc).AddTicks(679)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 418, DateTimeKind.Utc).AddTicks(682),
                            Description = "Focused discussions on specific topics",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Seminars",
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 418, DateTimeKind.Utc).AddTicks(683)
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImgPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 420, DateTimeKind.Utc).AddTicks(3755),
                            Description = "A hands-on workshop to learn Python programming from scratch.",
                            EndDate = new DateTime(2024, 10, 16, 16, 0, 0, 0, DateTimeKind.Utc),
                            ImgPath = "assets/images/gallery/gallery-less-eight.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 50.0,
                            StartDate = new DateTime(2024, 10, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Python Workshop",
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 420, DateTimeKind.Utc).AddTicks(3757)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 420, DateTimeKind.Utc).AddTicks(8812),
                            Description = "Explore the future of artificial intelligence with leading experts.",
                            EndDate = new DateTime(2025, 1, 20, 17, 0, 0, 0, DateTimeKind.Utc),
                            ImgPath = "assets/images/gallery/gallery-full-seven.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 30.0,
                            StartDate = new DateTime(2025, 1, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            Title = "AI Lecture Series",
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 420, DateTimeKind.Utc).AddTicks(8813)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 420, DateTimeKind.Utc).AddTicks(8826),
                            Description = "Showcasing the latest innovations in technology.",
                            EndDate = new DateTime(2025, 6, 12, 18, 0, 0, 0, DateTimeKind.Utc),
                            ImgPath = "assets/images/background/cta-ticket-bg.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 20.0,
                            StartDate = new DateTime(2025, 6, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Tech Exhibition 2025",
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 420, DateTimeKind.Utc).AddTicks(8826)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 420, DateTimeKind.Utc).AddTicks(8833),
                            Description = "A conference on cloud solutions and scalability.",
                            EndDate = new DateTime(2023, 11, 7, 17, 0, 0, 0, DateTimeKind.Utc),
                            ImgPath = "assets/images/background/homepage-one-banner.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 100.0,
                            StartDate = new DateTime(2023, 11, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Cloud Computing Conference",
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 420, DateTimeKind.Utc).AddTicks(8834)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 420, DateTimeKind.Utc).AddTicks(8840),
                            Description = "Learn about the latest trends in cybersecurity.",
                            EndDate = new DateTime(2026, 3, 15, 15, 0, 0, 0, DateTimeKind.Utc),
                            ImgPath = "assets/images/background/timer-bg.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Price = 40.0,
                            StartDate = new DateTime(2026, 3, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Cybersecurity Seminar",
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 420, DateTimeKind.Utc).AddTicks(8841)
                        });
                });

            modelBuilder.Entity("DataLayer.Models.EventAgenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("EventAgendas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(918),
                            Date = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(919)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(2668),
                            Date = new DateTime(2024, 10, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(2668)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(2678),
                            Date = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 2,
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(2679)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(2683),
                            Date = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 3,
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(2684)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(2688),
                            Date = new DateTime(2025, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 3,
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(2688)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(2692),
                            Date = new DateTime(2023, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 4,
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(2693)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(2697),
                            Date = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 5,
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(2697)
                        });
                });

            modelBuilder.Entity("DataLayer.Models.EventContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventAgendaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SpeakerId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EventAgendaId");

                    b.HasIndex("SpeakerId");

                    b.ToTable("EventContent");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(4206),
                            EventAgendaId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            SpeakerId = 1,
                            StartTime = new TimeOnly(10, 0, 0),
                            Subject = "Introduction to Python Programming",
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(4207)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(7012),
                            EventAgendaId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            SpeakerId = 3,
                            StartTime = new TimeOnly(14, 0, 0),
                            Subject = "Python for Data Science",
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(7013)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(7020),
                            EventAgendaId = 2,
                            IsActive = true,
                            IsDeleted = false,
                            SpeakerId = 1,
                            StartTime = new TimeOnly(11, 0, 0),
                            Subject = "Advanced Python Techniques",
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(7021)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(7024),
                            EventAgendaId = 3,
                            IsActive = true,
                            IsDeleted = false,
                            SpeakerId = 2,
                            StartTime = new TimeOnly(14, 0, 0),
                            Subject = "Machine Learning Fundamentals",
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(7025)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(7028),
                            EventAgendaId = 3,
                            IsActive = true,
                            IsDeleted = false,
                            SpeakerId = 4,
                            StartTime = new TimeOnly(16, 0, 0),
                            Subject = "AI in Cloud Computing",
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(7028)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(7031),
                            EventAgendaId = 4,
                            IsActive = true,
                            IsDeleted = false,
                            SpeakerId = 1,
                            StartTime = new TimeOnly(9, 30, 0),
                            Subject = "Innovations in Software Development",
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(7032)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(7035),
                            EventAgendaId = 4,
                            IsActive = true,
                            IsDeleted = false,
                            SpeakerId = 2,
                            StartTime = new TimeOnly(13, 0, 0),
                            Subject = "AI-Powered Innovations",
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(7036)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(7038),
                            EventAgendaId = 5,
                            IsActive = true,
                            IsDeleted = false,
                            SpeakerId = 4,
                            StartTime = new TimeOnly(10, 0, 0),
                            Subject = "Cloud Solutions Showcase",
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(7039)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(7042),
                            EventAgendaId = 6,
                            IsActive = true,
                            IsDeleted = false,
                            SpeakerId = 4,
                            StartTime = new TimeOnly(9, 0, 0),
                            Subject = "Scalable Cloud Architectures",
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(7042)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(7045),
                            EventAgendaId = 6,
                            IsActive = true,
                            IsDeleted = false,
                            SpeakerId = 5,
                            StartTime = new TimeOnly(11, 30, 0),
                            Subject = "Securing Cloud Infrastructure",
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(7046)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(7049),
                            EventAgendaId = 7,
                            IsActive = true,
                            IsDeleted = false,
                            SpeakerId = 5,
                            StartTime = new TimeOnly(10, 0, 0),
                            Subject = "Ethical Hacking Techniques",
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(7049)
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Speaker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Speakers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Software engineering expert with over 10 years of experience.",
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 419, DateTimeKind.Utc).AddTicks(6292),
                            ImgPath = "assets/images/speakers/single-speaker.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Ahmed Khaled",
                            Specialization = "Software Development",
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 419, DateTimeKind.Utc).AddTicks(6295)
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Data science enthusiast and AI researcher.",
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 419, DateTimeKind.Utc).AddTicks(9462),
                            ImgPath = "assets/images/speakers/speaker-five.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mohamed Ali",
                            Specialization = "Data Science",
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 419, DateTimeKind.Utc).AddTicks(9463)
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Specialist in educational workshops with a focus on interactive learning.",
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 419, DateTimeKind.Utc).AddTicks(9471),
                            ImgPath = "assets/images/speakers/speaker-full-five.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Omar Mostafa",
                            Specialization = "Education",
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 419, DateTimeKind.Utc).AddTicks(9472)
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Expert in cloud computing and distributed systems.",
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 419, DateTimeKind.Utc).AddTicks(9476),
                            ImgPath = "assets/images/speakers/speaker-full-one.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Hassan Ibrahim",
                            Specialization = "Cloud Computing",
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 419, DateTimeKind.Utc).AddTicks(9477)
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Cybersecurity specialist with a focus on ethical hacking.",
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 419, DateTimeKind.Utc).AddTicks(9543),
                            ImgPath = "assets/images/speakers/speaker-full-three.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Youssef Sami",
                            Specialization = "Cybersecurity",
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 419, DateTimeKind.Utc).AddTicks(9544)
                        });
                });

            modelBuilder.Entity("DataLayer.Models.SpeakerSocialMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<int>("SpeakerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SpeakerId");

                    b.ToTable("SpeakerSocialMedias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(8731),
                            IsActive = true,
                            IsDeleted = false,
                            Platform = 2,
                            SpeakerId = 1,
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 421, DateTimeKind.Utc).AddTicks(8731),
                            Url = "https://linkedin.com/in/ahmedkhaled"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 422, DateTimeKind.Utc).AddTicks(905),
                            IsActive = true,
                            IsDeleted = false,
                            Platform = 1,
                            SpeakerId = 1,
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 422, DateTimeKind.Utc).AddTicks(906),
                            Url = "https://twitter.com/ahmedkhaled"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 422, DateTimeKind.Utc).AddTicks(912),
                            IsActive = true,
                            IsDeleted = false,
                            Platform = 1,
                            SpeakerId = 2,
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 422, DateTimeKind.Utc).AddTicks(913),
                            Url = "https://twitter.com/mohamedali"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 422, DateTimeKind.Utc).AddTicks(917),
                            IsActive = true,
                            IsDeleted = false,
                            Platform = 3,
                            SpeakerId = 3,
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 422, DateTimeKind.Utc).AddTicks(918),
                            Url = "https://instagram.com/omarmostafa"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 422, DateTimeKind.Utc).AddTicks(922),
                            IsActive = true,
                            IsDeleted = false,
                            Platform = 2,
                            SpeakerId = 4,
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 422, DateTimeKind.Utc).AddTicks(923),
                            Url = "https://linkedin.com/in/hassanibrahim"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 422, DateTimeKind.Utc).AddTicks(1061),
                            IsActive = true,
                            IsDeleted = false,
                            Platform = 1,
                            SpeakerId = 5,
                            UpdatedAt = new DateTime(2025, 7, 19, 10, 33, 11, 422, DateTimeKind.Utc).AddTicks(1062),
                            Url = "https://twitter.com/youssefsami"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Wishlist", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = "ad31d12d-e3ac-45c7-94e6-a9bb48aaf789",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "3edcc6f2-c30c-471a-80fb-6a9786ae3470",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DataLayer.Models.Event", b =>
                {
                    b.HasOne("DataLayer.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DataLayer.Models.EventAgenda", b =>
                {
                    b.HasOne("DataLayer.Models.Event", "Event")
                        .WithMany("Agenda")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DataLayer.Models.EventContent", b =>
                {
                    b.HasOne("DataLayer.Models.EventAgenda", "EventAgenda")
                        .WithMany("EventAgendaContents")
                        .HasForeignKey("EventAgendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Models.Speaker", "Speaker")
                        .WithMany("EventContents")
                        .HasForeignKey("SpeakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventAgenda");

                    b.Navigation("Speaker");
                });

            modelBuilder.Entity("DataLayer.Models.SpeakerSocialMedia", b =>
                {
                    b.HasOne("DataLayer.Models.Speaker", null)
                        .WithMany("SocialMedias")
                        .HasForeignKey("SpeakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataLayer.Models.Wishlist", b =>
                {
                    b.HasOne("DataLayer.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DataLayer.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DataLayer.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DataLayer.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataLayer.Models.Event", b =>
                {
                    b.Navigation("Agenda");
                });

            modelBuilder.Entity("DataLayer.Models.EventAgenda", b =>
                {
                    b.Navigation("EventAgendaContents");
                });

            modelBuilder.Entity("DataLayer.Models.Speaker", b =>
                {
                    b.Navigation("EventContents");

                    b.Navigation("SocialMedias");
                });
#pragma warning restore 612, 618
        }
    }
}
